
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import java.net.*;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author a80052136
 */
public class sendEmail extends javax.swing.JFrame {
    private ArrayList<String> summaryList;
    private SubcontractorDA da;
    private String subcon;
    private ArrayList<Subcontractor> conList;
    /**
     * Creates new form sendEmail
     */
    public sendEmail(String subcon) {
        initComponents();
        receiverLbl.setText(subcon);
        this.subcon = subcon;
        da = new SubcontractorDA();
        centreWindow(this);
        conList = da.getAllSubcontractor();
        if (conList.isEmpty() ) {
            receiverCombo.addItem("");
            receiverCombo.setEnabled(false);
        }
        
        for (Subcontractor s: conList) {
            receiverCombo.addItem(s.getEmail());
        }
        this.summaryList = summaryList;
        subjectTF.setText("BIS Report Submission Status");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        messageTA = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        receiverCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        subjectTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        receiverLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sendBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        messageTA.setColumns(20);
        messageTA.setRows(5);
        jScrollPane1.setViewportView(messageTA);

        jLabel2.setText("Receiver: ");

        receiverCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Subject: ");

        subjectTF.setText("jTextField1");

        jLabel1.setText("Email: ");

        receiverLbl.setText("contractor name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiverLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectTF, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receiverCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(receiverLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(subjectTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(receiverCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel5.setText("Message: ");

        sendBtn.setText("Send");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(sendBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendBtn)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // This function will centre the window
    private void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }
    
    private void receiverComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverComboActionPerformed
    
    private String getSummaryStr() {
        int i = 0, j = 0, smallest = 0;
        String summary = "";
        String[] category = {"1-FOP", "2-OPTI", "3-BSTR", "4-FM", 
            "5-PREFIX"};
        for (j = 0; j <= 4; j++) {
            for (i = smallest; i <= smallest + 1; i++) {
                if (i%2 == 0) {
                    summary += category[j] + " \t\tPending\t" + summaryList.get(i);
                }
                else {
                    summary += "\tsubmission\t" + summaryList.get(i) + "\tResubmission\n";
                }
            }
            smallest += 2;
        }
        return summary;
    }
    
    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        try{
            String host ="smtpscn.huawei.com" ;
            String user = "a80052136";
            String pass = "HelpB1600693!";
            // Recipient's email ID
            String to = "adrianf.wei@huawei.com";
            // Sender's email ID
            String from = "adrianf.wei@huawei.com";
            String subject = subjectTF.getText();
            String messageText = getSummaryStr();
            boolean sessionDebug = false;

            Properties props = System.getProperties(); // to set different type of properties

            props.put("mail.smtp.starttls.enable", "true");
            props.put("mail.smtp.host", host);
            props.put("mail.smtp.port", "587");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.required", "true");
            props.put("mail.smtp.ssl.trust", "smtpscn.huawei.com");

            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            Session mailSession = Session.getDefaultInstance(props, null);
            mailSession.setDebug(sessionDebug);
            
            // Create a default MimeMessage oject
            Message msg = new MimeMessage(mailSession);
            
            // Set From: heder field of the header
            msg.setFrom(new InternetAddress(from));
            
            // Set To: header filed of the header
            InternetAddress[] address = {new InternetAddress(to)}; // address of sender
            msg.setRecipients(Message.RecipientType.TO, address); // receiver email
            
            // Set Subject: header field
            msg.setSubject(subject); 
            msg.setSentDate(new Date()); // message send date
            
            // Create the message part
            BodyPart msgBodyPart = new MimeBodyPart();
            
            // Now set the actual message
            msgBodyPart.setText(messageText);
            
            // Create a multipar message
            Multipart multipart = new MimeMultipart();
            
            // Set text message part
            multipart.addBodyPart(msgBodyPart);
            
            // Part two is attachment
            msgBodyPart = new MimeBodyPart();
            String filename = "C:\\Users\\a80052136\\Documents\\NetBeansProjects\\sendMessage\\" + 
                    subcon + ".xlsx";
            DataSource source = new FileDataSource(filename);
            msgBodyPart.setDataHandler(new DataHandler(source));
            msgBodyPart.setFileName(source.getName());
            //msgBodyPart.setFileName(filename);
            multipart.addBodyPart(msgBodyPart);

            // Send the complete message parts
            msg.setContent(multipart);
                       
            //msg.setText(messageText); // actual message

           Transport transport=mailSession.getTransport("smtp"); //server through which we are going to send msg
           transport.connect(host, user, pass); // we need because we have to authenticate sender email and password
           transport.sendMessage(msg, msg.getAllRecipients());
           transport.close();
           System.out.println("message send successfully");
        }catch(Exception ex)
        {
            System.out.println(ex); // if any error occur then error message will print
        }
        /**
        Desktop desktop;
        if (Desktop.isDesktopSupported() 
            && (desktop = Desktop.getDesktop()).isSupported(Desktop.Action.MAIL)) {
            URI mailto = null;
            String email = (String) receiverCombo.getSelectedItem();
            String subject = subjectTF.getText();
            String summary = getSummaryStr();
            String message = "";
            if (messageTA.getText().equalsIgnoreCase("")) {
                message = "Below are the latest BIS Report submission "
                    + "status:\n\n";
            }
            else {
                message = messageTA.getText() + "\n\n";
            }
      
            String body = ""
                    + message + summary + "\n\n"
                    + "Attached can find the details acceptance plan information."
                    + "\n\nThank you.";
            body = body.replaceAll(" ", "%20");
            body = body.replaceAll("\n", "%0A");
            body = body.replaceAll("\t", "%09");
            body = body.replaceAll(":", "%3A");
            body = body.replaceAll("\\.", "%2E");
            body = body.replaceAll(",", "%2C");
            subject = subject.replaceAll(" ", "%20");
            subject = subject.replaceAll("\n", "%0A");
            subject = subject.replaceAll("\t", "%09");
            subject = subject.replaceAll(":", "%3A");
            subject = subject.replaceAll("\\.", "%2E");
            subject = subject.replaceAll(",", "%2C");
            try {
                mailto = new URI("mailto:" + email + "?subject=" + subject + 
                        "&body=" + body);
            } catch (URISyntaxException ex) {
                Logger.getLogger(sendEmail.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                desktop.mail(mailto);
            } catch (IOException ex) {
                Logger.getLogger(sendEmail.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
          // TODO fallback to some Runtime.exec(..) voodoo?
          throw new RuntimeException("desktop doesn't support mailto; mail is dead anyway ;)");
        }
        */
    }//GEN-LAST:event_sendBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageTA;
    private javax.swing.JComboBox<String> receiverCombo;
    private javax.swing.JLabel receiverLbl;
    private javax.swing.JButton sendBtn;
    private javax.swing.JTextField subjectTF;
    // End of variables declaration//GEN-END:variables
}
